name: "Kodehode"
description: "En blogg"

url: "http://kodehode.no"

markdown: kramdown
permalink: pretty
highlighter: "pygments"

defaults:
  -
    scope:
      path: "" # Match all files
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "posts"
